// GENERATED by scripts/copy-team-logos.mjs — re-run it instead of editing by hand.
/**
 * Maps team names (exactly as stored in `matches.team1` / `matches.team2`,
 * i.e. liiga.fi's `teamName`) to their logo files in public/teams/.
 * `dark` exists only when liiga.fi has a separate dark-background variant;
 * otherwise `light` is used in both themes. `Flag` (src/components/flag.tsx)
 * falls back to these when a team has no country flag.
 */
export type TeamLogo = { light: string; dark?: string };

export const TEAM_LOGOS: Record<string, TeamLogo> = {
  "HIFK": { light: "/teams/hifk.webp" },
  "HPK": { light: "/teams/hpk.webp" },
  "Ilves": { light: "/teams/ilves.webp" },
  "Jokerit": { light: "/teams/jokerit.webp" },
  "Jukurit": { light: "/teams/jukurit.webp" },
  "JYP": { light: "/teams/jyp.webp" },
  "K-Espoo": { light: "/teams/k-espoo.webp" },
  "KalPa": { light: "/teams/kalpa.webp" },
  "KooKoo": { light: "/teams/kookoo.webp" },
  "Kärpät": { light: "/teams/karpat.webp" },
  "Lukko": { light: "/teams/lukko.png", dark: "/teams/lukko-dark.png" },
  "Pelicans": { light: "/teams/pelicans.webp" },
  "SaiPa": { light: "/teams/saipa.webp" },
  "Sport": { light: "/teams/sport.webp" },
  "Tappara": { light: "/teams/tappara.webp" },
  "TPS": { light: "/teams/tps.webp" },
  "Ässät": { light: "/teams/assat.webp" },
};
