import type { MetadataRoute } from "next";

// Web app manifest (Next.js metadata route — served at /manifest.webmanifest
// and linked from every page's <head> automatically). Lets "Add to Home
// Screen" open the app full-screen on /matches. The icons are the app's one
// sport-neutral mark (generated by scripts/make-app-icons.mjs, like every other
// icon file) since the app covers several competitions; iOS uses
// src/app/apple-icon.png instead of these.
//
// Colors are the app's tokens from globals.css, as hex: the dark theme's
// --background (the app defaults to dark) and --green.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Friendly Bets",
    short_name: "Friendly Bets",
    description: "Sports prediction game for family & friends.",
    start_url: "/matches",
    display: "standalone",
    background_color: "#020509",
    theme_color: "#020509",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Android adaptive icons crop to a circle/squircle and only guarantee the
      // central 80% survives, so these use a smaller mark on the same
      // full-bleed green (see scripts/make-app-icons.mjs).
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
